# Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY watcher/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the watcher script
COPY watcher/watcher.py .

# Command to run the watcher script
CMD ["python", "watcher.py"]
